name: Python application

on:
  push:
    branches: [main]  # 触发 action 的分支
  pull_request:
    branches: [main]  # 触发 action 的 pull request
  workflow_dispatch:  # 支持手动触发

jobs:
  test:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 运行环境

    steps:
    - name: Check out repository
      uses: actions/checkout@v2  # 检出你的仓库内容

    - name: Set up Python
      uses: actions/upload-artifact@v4
      with:
        python-version: 3.8  # 配置 Python 版本，可以根据需要调整

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 安装项目的依赖

    - name: Run tests
      run: |
        # 这里假设你使用 pytest 进行测试
        pytest  # 运行你的测试（如果有的话）
        
    - name: Upload test results to GitHub
      if: always()  # 始终上传结果
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results.xml  # 假设你使用 XML 格式保存测试结果
